### ISSUE TITLE
Convert WAB Aloha widget

### ISSUE THREAD

**Issue by ERS-Long** [cmv/cmv-app#538] opened 2016-04-14 20:00 UTC
Hi, Tim:

I am in the very early phase to try to convert the following Aloha widget to CMV widget. 

http://gis.calhouncounty.org/WAB/V1.3/widgets/Aloha/index.html#

When i look at the widget.js file, the author referenced a list of 

  'jimu/BaseWidget',

  'jimu/dijit/TabContainer',
  'jimu/utils',

  'jimu/dijit/Message',
  'jimu/utils',
  'jimu/tokenUtils',

  'jimu/dijit/DrawBox',
  'jimu/dijit/LoadingShelter',
  'jimu/dijit/_Transparency'

Can you give me a suggestion on how to handle/migrate all those to stuff we can use in CMV? 

Thanks a lot!

**Comment by tmcgee** [comment] 2016-04-14 20:25
@ERS-Long you have excellent timing. ;) 

I am about to release a new beta mixin for cmv that allows you to use many (most?) WAB `inPanel` widgets in CMV with minimal to no conversion. Most of the conversion is functionality that expect a web map. The majority of widgets I have looked at so far interact with the ESRI map and layers so need no conversion at all.

I have this mixin deployed for one customer with 2 widgets in production. I did basic testing with a dozen or so other custom and out of the box WAB widgets with positive results. Most of the issues so far are conflicts with themes (cmv vs wab). I:ve addressed some of that already. It will be another useful test to see how well it works for this Aloha widget. I'll add a repo in the next couple of days to demonstrate the concept. How's that sound?

**Comment by tmcgee** [comment] 2016-04-14 20:25
@ERS-Long you have excellent timing. ;) 

I am about to release a new beta mixin for cmv that allows you to use many (most?) WAB `inPanel` widgets in CMV with minimal to no conversion. Most of the conversion is functionality that expect a web map. The majority of widgets I have looked at so far interact with the ESRI map and layers so need no conversion at all.

I have this mixin deployed for one customer with 2 widgets in production. I did basic testing with a dozen or so other custom and out of the box WAB widgets with positive results. Most of the issues so far are conflicts with themes (cmv vs wab). I:ve addressed some of that already. It will be another useful test to see how well it works for this Aloha widget. I'll add a repo in the next couple of days to demonstrate the concept. How's that sound?

**Comment by ERS-Long** [comment] 2016-04-14 20:30
@tmcgee That is wonderful to hear, as always from you. I cannot wait to try it out with your new approach. Thanks!!

**Comment by tmcgee** [comment] 2016-04-16 16:27
@ERS-Long Good news. This is another WAB widget that works in CMV without any modifications to the widget. I am adding more tests/examples to the repo locally then will push to [this github repo](https://github.com/tmcgee/cmv-wab-widgets). I will close this issue and the discussion can continue over there.

![image](https://cloud.githubusercontent.com/assets/200780/14573635/141af126-030b-11e6-932d-32dbe4a98000.png)

**Closed by tmcgee** 2016-04-16 16:28 UTC

**Comment by ERS-Long** [comment] 2016-04-16 18:17
That is fantttttttastic!!!!

Can express how happy I am because we need that widget working in cmv badly.

Thank you so much!

**Comment by tmcgee** [comment] 2016-04-16 20:33
@ERS-Long I have updated the [repo](https://github.com/tmcgee/cmv-wab-widgets) with full code and some docs. The demos are not working from github.io at present but they do work locally.

**Comment by ERS-Long** [comment] 2016-04-16 21:11
Hi, Tim:

I got it working locally. Really nice!

The only thing i noticed is if i turn on all the four panels, only the left panel loads. Not sure it is something i missed or something else.

I will try more wab widget this week and report it back.

Thank you so much!

**Comment by tmcgee** [comment] 2016-04-16 21:16
I think what you are seeing is not related to the WAB widget demos but within the develop branch of cmv-app. There are a few new quirks related to the pane config caused by the addition of the controller mixins. I may have already fixed what you are seeing or it may be a new issue.

**Comment by ERS-Long** [comment] 2016-04-16 23:13
My bad, after reload it, everything is in good shape. Thanks!
