### ISSUE TITLE
how to add search features to Geocoder

### ISSUE THREAD

**Issue by JudyZhou** [cmv/cmv-app#656] opened 2016-12-28 19:06 UTC
I need to add search features to Geocoder. I have done this in ESRI Search widget in web AppBuilder before. this time I added code into Geocoder.js like this, but search result return not found. Or is available a search widget including data search and geocoder? Please help!:
```javascript
 sources: [{
  locator: new Locator("http://cohgims.houstontx.gov/arcgis/rest/services/AddressLocators/Locator_composite/GeocodeServer"),
  name: "HOU PWE Locator",
  singleLineFieldName: "SingleLine",
  placeholder: "Enter Address or Intersection",
  countryCode: "",
  maxResults: 30,
  searchInCurrentMapExtent: false,
  highlightSymbol: new PictureMarkerSymbol("https://js.arcgis.com/3.18/esri/dijit/Search/images/search-pointer.png", 36, 36).setOffset(9, 18)
}, {
  "layerId": "RBH_wab_76_0",
  "url": "http://pwegis.houstontx.gov/arcgis/rest/services/PROD/RBH1/MapServer/4",
  "name": "CIP Projects",
  "placeholder": "Enter Project No. or Description",
  "searchFields": ["CIP_NO", "PRO_SCOPE"],
  "displayField": "CIP_NO",
  "exactMatch": false,
  "maxResults": 300,
  "type": "query"
}];
```

**Comment by tmcgee** [comment] 2016-12-29 06:38
@JudyZhou You can use the Esri Search widget with CMV just as you have done with the WAB. The Esri Geocoder widget has been deprecated by Esri so the Search widget is the preferred option. We have switched to the search widget in [CMV](https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/viewer.js#L287).

**Comment by JudyZhou** [comment] 2016-12-29 14:23
@tmcgee thank you for help! does CMV has search widget already? where can I download it?

**Comment by tmcgee** [comment] 2016-12-30 07:30
@JudyZhou I provided a link in my previous response to the line in the demo viewer.js where the Esri search widget is included. It is not a CMV widget. No downloading required.

**Comment by roemhildtg** [comment] 2017-01-05 16:56
I think this is actually a bug. Adding feature layer searches doesn't work in cmv due to the widget loader using `lang.clone` on the widget options.

[This documentation](https://developers.arcgis.com/javascript/3/jsapi/search-amd.html#sources) uses the `FeatureLayer` constructor in the source options. But the `clone` function cannot clone a FeatureLayer object, for example the following throws an error:

```javascript
lang.clone(new FeatureLayer('url'))
```

This can be reproduced in cmv using the config:
```javascript

        search: {
            include: true,
            type: 'domNode',
            path: 'esri/dijit/Search',
            srcNodeRef: 'geocoderButton',
            options: {
                map: true,
                mapRightClickMenu: true,
                enableInfoWindow: true,
                enableButtonMode: true,
                expanded: false,
                sources: [{
                    featureLayer: new FeatureLayer('/arcgis/rest/services/internal/assets/MapServer/12', {
                        outFields: ['cid', 'Shape', 'OBJECTID']
                    }),
                    searchFields: ['cid'],
                    suggestionTemplate: 'Structure Number: ${cid}',
                    exactMatch: false,
                    name: 'Storm Structure ID',
                    placeholder: 'Structure ID',
                    maxResults: 6,
                    maxSuggestions: 6,
                    enableSuggestions: true,
                    minCharacters: 0,
                    localSearchOptions: {distance: 5000}
                }]
            }
        },
```

@tmcgee is that `lang.clone` needed on the widget loader?

**Comment by tmcgee** [comment] 2017-01-06 23:21
@roemhildtg I don't have a problem including feature layers in the Esri Search widget and have used it often for clients. I will compare the example you provided above with one of my working versions and see if I can identify the difference.

**Comment by tmcgee** [comment] 2017-01-10 00:40
@roemhildtg I think the difference in our approaches may be that I do not include the search widget's options within `viewer.js` but within a separate file `search.js`. As a by-product my approach, the feature layer(s) in the widget's options do not get cloned.

As to why `lang.clone` is used with the widget config, that line pre-dates my involvement with the CMV project. I think we can just remove it because it is problematic for this Esri widget and potentially others - specifically those widgets that include Esri modules within their config options. As we've seen elsewhere, some of the  Esri modules don't handle cloning well.

@DavidSpriggs do you recall the original need for `lang.clone` in [this line](https://github.com/cmv/cmv-app/blob/develop/viewer/js/viewer/_WidgetsMixin.js#L45) and  any objections to not cloning the config?

**Comment by roemhildtg** [comment] 2017-01-10 14:42
I see, that would make sense since if you pass a string as the widget options, lang.clone won't be used on the actual options object.

**Comment by tmcgee** [comment] 2017-01-10 14:43
Correct

**Comment by roemhildtg** [comment] 2017-01-20 21:10
I don't think the `lang.clone` is necessary. I've taken it out on my end and things appear to be in working order. We should add this enhancement to the widget mixin to allow feature layers in the options properties.

**Comment by roemhildtg** [comment] 2017-06-29 17:26
closed in https://github.com/cmv/cmv-app/pull/736

**Closed by roemhildtg** 2017-06-29 17:26 UTC
Labels: enhancement, question

**Comment by gisnovice** [comment] 2017-09-07 15:26
Hello, can I add my own GeocodeServer to the search widget? I am trying for the search widget to also recognize APNs, or would it only be suited for the Find widget?

```
            search: {
                include: true,
                type: has('phone') ? 'titlePane' : 'ui',
                path: 'esri/dijit/Search',
                placeAt: has('phone') ? null : 'top-center',
                title: i18n.viewer.widgets.search,
                iconClass: 'fa-search',
                position: 0,
                options: {
                    map: true,
                    visible: true,
                    enableInfoWindow: true,
                    enableButtonMode: has('phone') ? false : true,
                    expanded: has('phone') ? true : false,
                    expanded: true,
                    defaultSource: 'http://gis.ci.oceanside.ca.us/gis/rest/services/AddressLocator_Composite2016/GeocodeServer'
                }
            },
```
