### ISSUE TITLE
width of editor popup

### ISSUE THREAD

**Issue by paulanergraz** [cmv/cmv-app#610] opened 2016-10-04 05:22 UTC
Where can i define the width of the editor popup?

I tried to find it in the css files but didn't find it.

Because it's a little bit to small (see screenshot).

Greetings Paul

![screenshot editor](https://cloud.githubusercontent.com/assets/13347735/19063449/3d35214c-8a03-11e6-869d-b327d114c576.png)

**Comment by tmcgee** [comment] 2016-10-04 05:34
@paulanergraz I think you are looking to set the width of Esri popup. Here's the css where that is set: https://github.com/cmv/cmv-app/blob/master/viewer/css/main.css#L246

**Comment by paulanergraz** [comment] 2016-10-04 06:00
Thanks for the fast response.

That was my first thought too.
But it only changes the size of the non editing popup.

When i start the editing session the popup is small again and the strange thing is the other popups are also small again see on the screenshots:

![step1](https://cloud.githubusercontent.com/assets/13347735/19064122/572cd630-8a08-11e6-8dbe-ade09720db26.png)

Here it works

![step2](https://cloud.githubusercontent.com/assets/13347735/19064123/5d1a6af8-8a08-11e6-8be5-6106340920aa.png)

now i am opening the editor the popup is small again

![step3](https://cloud.githubusercontent.com/assets/13347735/19064125/61336e0a-8a08-11e6-8b78-174acad8304a.png)

now the non editing popup is small again.

Link to the website: https://www.hgis-indias.net/cmv-app-master/editor/

**Comment by tmcgee** [comment] 2016-10-04 17:55
@paulanergraz I cannot access the website with the url you provided (domain possibly resolving differently for you?).

Based on the last screenshot, I am wondering if there is some other css set that is restricting the width of the esri popup. It looks like div with class `sizer` is sizing properly but constrained by a containing div. Perhaps The div with the class `esriPopupWrapper` has a width defined?

**Comment by paulanergraz** [comment] 2016-10-05 05:48
@tmcgee  interesting that the url is not working. I tried it on different Devices with different ISPs and I also changed the DNS Servers (I used the DNS of my ISPs, the DNS of Google and the DNS of OpenDNS)
the Ip Adress should be 5.175.5.248 if you ping www.hgis-indias.net

When i define a width at `esriPopupWrapper` this happens.
![step4](https://cloud.githubusercontent.com/assets/13347735/19102322/9712899e-8acf-11e6-9f9f-5c412c734b93.png)

When i change the width in the following code in Bugzilla it works. But I still don't know where the 350px are comming from 
```
<div class="esriPopup esriPopupVisible" style="visibility: visible; z-index: 40; left: 213px; top: 279px;">
<div class="esriPopupWrapper" style="position: absolute; left: 16px; top: -208.5px;">
<div class="sizer" style="width: 350px;">
<div class="sizer content" style="width: 350px;">
<div class="contentPane" style="max-height: 375px;">
</div>
<div class="sizer" style="width: 350px;">
<div class="pointer"></div>
</div>
<div class="outerPointer left"></div>
</div>
```
Changed the width to 800px
![step5](https://cloud.githubusercontent.com/assets/13347735/19102368/122cd3d2-8ad0-11e6-8086-74f159f70779.png)

**Comment by tmcgee** [comment] 2016-10-05 07:00
@paulanergraz It isn't a problem that the server name cannot be resolved. When I ping using that name, I do get the i.p. address you noted. 

The problem is I don't see the same page when accessing the website. When I click on the link you provided, this is what I see:

![image](https://cloud.githubusercontent.com/assets/200780/19103610/c05385da-8a8c-11e6-929a-176e73f43b1f.png)

For the css, try adding `!important` like this:

``` css
.esriPopup .sizer {
    width: 800px !important;
}
```
That worked for me. When you adjust the width of the popup, you may also need/want to adjust the width of the input text boxes within it. Something like this:

``` css
.esriAttributeInspector .dijitTextBox {
   width: 500px !important;
}
```

**Comment by paulanergraz** [comment] 2016-10-05 07:27
@tmcgee thanks `!important` did the job. Now everything is working fine.

Somehow you are opening the site on the old server with the IP 92.51.163.225.  strange because i changed the DNS Settings a month ago.

**Closed** 2016-10-05 07:28 UTC
